adding improper list and charlist support
localvore-today/secure_log_formatter pull request #11
Opened 2017-07-12 13:07 UTC by danturn

Sorry about the confusion. i got lost in branches

here's a PR with the 2 updates i made, supporting improper lists, and replacing matches inside charlists

Dan

2017-07-12 15:48 UTC, doomspork requested changes
This is great, thank you @danturn!  Just a couple small changes and we should be good 👍

2017-07-12 15:48 UTC, doomspork commented on lib/secure_log_formatter.ex
> +    case :io_lib.deep_char_list(data) do
Since this is matching on booleans, could you please use `if`?

2017-07-12 15:48 UTC, doomspork commented on lib/secure_log_formatter.ex
> +  def sanitize_list([], acc), do: acc |> Enum.reverse
Could you please make this (and line 89): `Enum.reverse(acc)`?

https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines

2017-07-12 15:48 UTC, doomspork commented on config/config.exs
> +  ~r/\d{3}-?\d{2}-?\d{4}/,
What are you thoughts on us pulling all of these patterns out into a separate file that can be loaded during compilation?

Should we remove this SSN pattern too?  It could potentially cover up generated numbers in some apps and I imagine few people deal with SSNs anyways.

2017-07-12 20:05 UTC, danturn commented
Hey @doomspork 

I made those changes, thanks for the feedback!

regarding the separate file, what's the advantage? are you just talking about loading that file for running the tests? I quite liked that there were examples in the project so you could see some ideas about what to do. 

not sure about removing the SSN, people will write their own filters so if they arent dealing with SSNs they dont need to include that? (we are only dealing with database passwords for sql server so our pattern list is just the one i added and we dont filter out SSNs, credit cards etc)

dan

2017-07-18 06:37 UTC, doomspork commented
Upon second though, we should leave it as-is.  Was a half baked idea 😁

2017-07-18 06:38 UTC, doomspork approved these changes

2017-07-18 06:38 UTC, merged

2017-07-18 06:42 UTC, doomspork commented
New version released @danturn, thanks again!